---
galaxy_info:
  author: yourusername
  description: Common server configuration for all nodes
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
dependencies: []
