---
all:
  children:
    webservers:
      hosts:
        web01:
          ansible_host: 127.0.0.1
          ansible_port: 2222
          ansible_ssh_private_key_file: "{{ vagrant_key_web1 }}"
        web02:
          ansible_host: 127.0.0.1
          ansible_port: 2200
          ansible_ssh_private_key_file: "{{ vagrant_key_web2 }}"
    databases:
      hosts:
        db01:
          ansible_host: 127.0.0.1
          ansible_port: 2201
          ansible_ssh_private_key_file: "{{ vagrant_key_db01 }}"
    monitoring:
      hosts:
        monitor01:
          ansible_host: 127.0.0.1
          ansible_port: 2202
          ansible_ssh_private_key_file: "{{ vagrant_key_monitor01 }}"
  vars:
    ansible_user: vagrant
    vagrant_key_web1: .vagrant/machines/web1/virtualbox/private_key
    vagrant_key_web2: .vagrant/machines/web2/virtualbox/private_key
    vagrant_key_db01: .vagrant/machines/db01/virtualbox/private_key
    vagrant_key_monitor01: .vagrant/machines/monitor01/virtualbox/private_key
